/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
    tutorialSidebar: [
        {
            type: "category",
            label: "About Monk",
            collapsed: false,
            items: [
                "welcome",
                "use-cases",
                "key-concepts",
                "comparison",
                "features",
                "support",
                "monk-privacy",
            ],
        },
        {
            type: "category",
            label: "Getting Started",
            collapsed: true,
            items: ["get-monk", "acc-and-auth"],
        },
        {
            type: "category",
            label: "Basics",
            collapsed: true,
            items: ["monk-in-10", "running-templates", "inspecting-workloads"],
        },
        {
            type: "category",
            label: "Deploy",
            collapsed: true,
            items: [
                "lifecycle/cluster-overview",
                "lifecycle/cluster-create-1",
                "lifecycle/cluster-operate-1",
                "lifecycle/cluster-switch-1",
                "lifecycle/running-templates-cluster",
            ],
        },
        {
            type: "category",
            label: "Develop Templates",
            collapsed: true,
            items: [
                "basic-app",
                "connecting-runnables",
                "readiness-and-dependency-checks",
                "persistent-storage",
                "config-files",
                "passing-secrets",
                "provisioning-via-templates",
                "affinity",
                "load-balancers",
                "hooks",
            ],
        },
        {
            type: "category",
            label: "Level Up",
            collapsed: true,
            items: ["k8s-migrate", "ci-cd", "multi-cloud", "cloud-provider"],
        },
        {
            type: "category",
            label: "Publish to MonkHub",
            collapsed: false,
            items: ["publishers", "publishing"],
        },
        {
            type: "category",
            label: "Case Studies",
            collapsed: false,
            items: ["cases/chainlink"],
        },
        {
            type: "category",
            label: "Troubleshooting",
            collapsed: false,
            items: ["troubleshooting/templates"],
        },
        {
            type: "category",
            label: "Reference",
            collapsed: false,
            items: [
                {
                    type: "category",
                    label: "MonkScript",
                    collapsed: true,
                    items: [
                        "monkscript/index",
                        "monkscript/working",
                        {
                            type: "category",
                            label: "YAML",
                            collapsed: true,
                            items: [
                                "monkscript/yaml/index",
                                "monkscript/yaml/runnables",
                                "monkscript/yaml/groups",
                                "monkscript/yaml/services",
                            ],
                        },
                        {
                            type: "category",
                            label: "Scripting",
                            collapsed: true,
                            items: [
                                "monkscript/scripting/index",
                                "monkscript/scripting/cheatsheet",
                                {
                                    type: "category",
                                    label: "Operators",
                                    collapsed: true,
                                    items: [
                                        "monkscript/scripting/operators/HTTP",
                                        "monkscript/scripting/operators/JSON-RPC",
                                        "monkscript/scripting/operators/JSON",
                                        "monkscript/scripting/operators/actions",
                                        "monkscript/scripting/operators/boolean",
                                        "monkscript/scripting/operators/containers",
                                        "monkscript/scripting/operators/internals",
                                        "monkscript/scripting/operators/math",
                                        "monkscript/scripting/operators/network",
                                        "monkscript/scripting/operators/numbers",
                                        "monkscript/scripting/operators/random",
                                        "monkscript/scripting/operators/strings",
                                        "monkscript/scripting/operators/types",
                                        "monkscript/scripting/operators/variables",
                                    ],
                                },
                            ],
                        },
                    ],
                },
                {
                    type: "category",
                    label: "CLI",
                    collapsed: true,
                    items: ["cli/monk", "cli/monkd"],
                },
                "gui/index",
            ],
        },
    ],
};
